"""Domain entities for Hierarchical Model Execution Provenance & Evidence Ledger."""

from __future__ import annotations
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field


class ExecutionType(str, Enum):
    REAL_INFERENCE = "REAL_INFERENCE"
    REAL_LIBRARY = "REAL_LIBRARY"
    DETERMINISTIC_ALGORITHM = "DETERMINISTIC_ALGORITHM"
    CACHED_RESULT = "CACHED_RESULT"
    SYNTHETIC_FIXTURE = "SYNTHETIC_FIXTURE"


class ComparisonStatus(str, Enum):
    COMPATIBLE = "COMPATIBLE"
    RELATED_BUT_DIFFERENT_DOCUMENT_TYPES = "RELATED_BUT_DIFFERENT_DOCUMENT_TYPES"
    SPECIALIZED_COMPARISON = "SPECIALIZED_COMPARISON"
    INCOMPATIBLE = "INCOMPATIBLE"
    UNKNOWN = "UNKNOWN"


class ComparisonMode(str, Enum):
    DOCUMENT_DOCUMENT = "DOCUMENT_DOCUMENT"
    SAME_TEMPLATE_OR_FAMILY = "SAME_TEMPLATE_OR_FAMILY"
    DOCUMENT_TAMPER = "DOCUMENT_TAMPER"
    FACE_IDENTITY = "FACE_IDENTITY"
    GENERIC_IMAGE = "GENERIC_IMAGE"


class ModelExecutionProvenance(BaseModel):
    """Hierarchical and inspectable provenance for an executed neural model or library."""

    source: str
    repository: str | None = None
    model_name: str
    checkpoint: str | None = None
    version: str | None = "1.0.0"
    execution_type: ExecutionType
    device: str = "cpu"
    precision: str = "fp32"
    runtime_ms: float
    raw_confidence: float | None = None
    calibrated_confidence: float | None = None
    evidence_quality: str = "HIGH"  # "HIGH", "MEDIUM", "LOW", "CONTRADICTORY"
    input_dimensions: list[int] | None = None
    output_dimensions: list[int] | None = None
    document_id: str | None = None
    page_index: int = 0
    region_id: str | None = None


class EvidenceLedgerEntry(BaseModel):
    """Detailed diagnostic ledger entry for a single comparison evidence dimension."""

    dimension: str
    raw_value: float | None
    calibrated_value: float | None
    role: str  # "PRIMARY_DISCRIMINATOR", "SECONDARY_SIGNAL", "GATED_OUT", "MODALITY_GATE"
    evidence_quality: str  # "HIGH", "MEDIUM", "LOW", "CONTRADICTORY"
    strength: str = "HIGH"  # "VERY_HIGH", "HIGH", "MEDIUM", "LOW", "VERY_LOW"
    confidence: float = 0.95
    applicability: str = "APPLICABLE"  # "APPLICABLE", "GATED_OUT", "CONDITIONED_SECONDARY", "INSUFFICIENT_COVERAGE"
    reason: str
    used_in_final_decision: bool
    provenance: ModelExecutionProvenance | None = None


class CalculationTrace(BaseModel):
    """Authoritative step-by-step mathematical trace generated by backend."""

    formula_version: str = "3.0.0"
    raw_inputs: dict[str, Any] = Field(default_factory=dict)
    applicable_dimensions: list[str] = Field(default_factory=list)
    gates_evaluated: list[str] = Field(default_factory=list)
    base_score: float = 0.0
    negative_multiplier: float = 1.0
    fused_probability: float | None = None
    decision_thresholds: dict[str, float] = Field(default_factory=dict)
    final_decision: str = "DIFFERENT_DOCUMENTS"
    final_similarity: float | None = None


class InputDescriptor(BaseModel):
    modality: str  # "DOCUMENT" | "PHOTOGRAPH" | "ID_DOCUMENT" | "UNKNOWN"
    document_type: str | None = None
    confidence: float = 0.95
    document_likelihood: float = 0.0
    photo_likelihood: float = 0.0
    rationale: str = ""


class LocalizedDifference(BaseModel):
    diff_id: str
    change_type: str  # "VALUE_CHANGED", "REGION_ADDED", "REGION_REMOVED", "LAYOUT_SHIFT", "FORENSIC_DELTA"
    field_key: str | None = None
    page_number: int = 1
    bounding_box: list[list[float]] = Field(default_factory=list)
    before_value: Any = None
    after_value: Any = None
    confidence: float = 0.95
    explanation: str = ""
    evidence_references: list[str] = Field(default_factory=list)


class ComparisonDimensions(BaseModel):
    visual_similarity: float | None = None
    structural_similarity: float | None = None
    text_similarity: float | None = None
    semantic_similarity: float | None = None
    template_similarity: float | None = None
    forensic_similarity: float | None = None
    layout_similarity: float | None = None
    entity_similarity: float | None = None
    local_feature_inliers: float | None = None
    layout_graph_similarity: float | None = None


class ModalityAwareComparisonResult(BaseModel):
    status: ComparisonStatus
    mode: ComparisonMode | None = None
    decision: str = "DIFFERENT_DOCUMENTS"
    decision_confidence: float = 0.99
    reason: str = ""
    similarity: float | None = None  # Calibrated secondary similarity
    confidence: float = 0.95
    dimensions: ComparisonDimensions = Field(default_factory=ComparisonDimensions)
    differences: list[LocalizedDifference] = Field(default_factory=list)
    positive_evidence: list[str] = Field(default_factory=list)
    negative_evidence: list[str] = Field(default_factory=list)
    evidence_vector: dict[str, float | None] = Field(default_factory=dict)
    evidence_ledger: list[EvidenceLedgerEntry] = Field(default_factory=list)
    calculation_trace: CalculationTrace | None = None
    model_provenances: list[ModelExecutionProvenance] = Field(default_factory=list)
    field_alignment_status: str = "NOT_APPLICABLE"
    verdict: str = "NOT COMPARABLE"
    input_a: InputDescriptor | None = None
    input_b: InputDescriptor | None = None
    explanation: str = ""
    available_action: str | None = None
    calibration_version: str = "3.0.0"
